version: "3.8"

services:
  django:
    build: .
    command: sh -c "gunicorn --bind 0.0.0.0:8000 MorphViewBlog.wsgi"
#    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - DOMAIN_NAME=${DOMAIN_NAME}
#    volumes:
#      - /MorphViewBlog:/MorphView
#      - /MorphViewBlog/static:/MorphView/static
    expose:
      - 8000
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - postgres
      - redis
    networks:
      - default

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    ports:
      - "5433:5432"
    networks:
      - default
    expose:
      - 5432

  redis:
    image: redis:latest
    restart: always
    entrypoint: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD} --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - /redis/appdata/redis/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default
    depends_on:
      - postgres
    expose:
      - 6379

#  certbot:
#    image: certbot/certbot
#    volumes:
#      - ./persistentdata/certbot/conf:/etc/letsencrypt
#      - ./persistentdata/certbot/www:/var/www/certbot

  nginx:
    image: nginx
    restart: always
    depends_on:
      - django
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf-d/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./MorphViewBlog/static/:/var/www/html/static/
      - ./MorphViewBlog/media/:/var/www/html/media/
      - ./persistentdata/certbot/conf:/etc/letsencrypt
      - ./persistentdata/certbot/www:/var/www/certbot
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}


networks:
  default:
    driver: bridge