version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    ports:
      - "5433:5432"
    networks:
      - default

networks:
  default:
    driver: bridge