version: "3.3"

services:
  django:
    build: .
    command: sh -c "gunicorn --bind 0.0.0.0:8000 MorphViewBlog.wsgi"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - ./MorphViewBlog/static/:/var/www/html/static/
      - ./MorphViewBlog/media/:/var/www/html/media/
    expose:
      - 8000
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - postgres
      - redis
    networks:
      - default

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    ports:
      - "5433:5432"
    networks:
      - default
    expose:
      - 5432

  redis:
    image: redis:latest
    restart: always
    entrypoint: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD} --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - /redis/appdata/redis/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default
    depends_on:
      - postgres
    expose:
      - 6379

  nginx:
    build:
      context: ./nginx-conf-d
    restart: always
    depends_on:
      - django
    ports:
      - "80:80"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx-conf-d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./MorphViewBlog/static/:/var/www/html/static/
      - ./MorphViewBlog/media/:/var/www/html/media/
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}


networks:
  default:
    driver: bridge